apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: show-jim-gitops
  description: This is GitOps manifest for show-jim   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: show-jim
    janus-idp.io/tekton: show-jim 
    backstage.io/kubernetes-id: show-jim 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:show-jim
