apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: show-jim
  janus-idp.io/tekton: show-jim
  backstage.io/kubernetes-id: show-jim
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: show-jim
resources: 
- deployment.yaml
- route.yaml
- service.yaml
