apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: show-jim
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: show-jim 
  name: show-jim
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: show-jim 
